apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingress-nginx.name" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}-controller
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
data:
  add-headers: {{ .Release.Namespace }}/{{ include "ingress-nginx.name" . }}-custom-add-headers
  proxy-set-headers: {{ .Release.Namespace }}/{{ include "ingress-nginx.name" . }}-custom-proxy-headers
