apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress-nginx.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
